### ISSUE TITLE
RestSharp 106.1.0 not using system proxy in .NET Framework

### ISSUE THREAD

**Issue by rogerdc** [restsharp/RestSharp#1043]
## Expected Behavior
When using RestSharp 106.1.0 in a project for the .NET Framework, the system proxy should be used and all requests should be routed through it. In this specific case, I'm using Fiddler as a local proxy. Web browsers are routing through this Proxy.

## Actual Behavior
Traffic from RestSharp is evidently not routed through the proxy and not picked up by Fiddler.

## Steps to Reproduce the Problem

  1. Create a .NET Framework project using RestSharp. I used https://github.com/rogerdc/RestSharpProxyTestForDotNETFramework. You can obtain your own key for the Dark Sky API at https://darksky.net/dev/register.
  2. Run Fiddler to set up a local proxy (https://www.telerik.com/fiddler)
  3. Run the console application in the project to send API requests to Dark Sky.

## Specifications

  - Version: 106.1.0
  - Platform: Windows 10, Visual Studio 2017 Community
  - Subsystem:

## StackTrace
None.

**Comment by teban1812** [comment]
Same here with 106.1.0 and .Net Core 2.0

**Comment by alexeyzimarev** [comment]
Can you guys check the latest alpha, I made some updates addressing the default proxy issue.

**Comment by rogerdc** [comment]
Retested with 106.2.0 and I can see my .NET Framework requests in Fiddler now.

Great work. 

I'm holding off on closing until @teban1812 checks with his .NET Core requests.

**Comment by alexeyzimarev** [comment]
Referring to #1061 

.NET Core will not support system proxy. Full framework does.

**Comment by ViktorHofer** [comment]
@alexeyzimarev please try using the default proxy again with the latest 2.0 bits. We fixed something related to this in on of the servicing releases: https://github.com/dotnet/corefx/pull/23885

**Comment by sirkris** [comment]
Is there a status update on this?  I have an open request to add proxy support to my .NET Standard library that uses RestSharp and this is blocking me.  Is the problem still that .NET Core doesn't support it?  The most recent comment from just over a year ago suggests there may be a solution.

**Comment by sirkris** [comment]
It's also worth noting that this thread is currently the top result on Google for the search query, "restsharp proxy example".  That's how I found it.

**Comment by alexeyzimarev** [comment]
@sirkris not sure what the issue is at the moment. We try getting the system proxy and we ignore if we get `PlatformNotSupportedException`. I tested it in Windows with Fiddler on both Core and full .NET and I had no issues.

**Comment by nmg196** [comment]
In .NET Core 3.1, RestSharp 106.11.4  ignores the Windows system proxy (eg Fiddler).  
It works if I specify it explicity, but it would be better if it picked it up by default the same way browsers do.

**Comment by DavidMartinSerrano** [comment]
I´m using restsharp on a WPF project for calling a net core 3.1 api...Everything works ok except the proxy:
public void AddProxy(string ipPuerto, string usuario, string pass)
        {
            var proxyURI = new Uri($"http://{ipPuerto}");
            ICredentials credentials = new NetworkCredential(usuario, pass);
            var proxy = new WebProxy(proxyURI, false, null, credentials);
            Client.Proxy = proxy;
            GlobalVariables.UsaProxy = true;
        }

It just ignores totally the proxy...I´m trying that proxy from wcf clients, from postman, and is working as expected...but, here is simply beign ignored.....I have the version 106.11.7 (latest at the moment) .... I have tried by all means (change httprequest.Default proxy, etc....) and nothing works...Can you please help guys???

Thanks

**Comment by RichardNobel** [comment]
I'm using RestSharp v106.11.7 and the request goes through (Squid) proxy server, but the Credentials are not picked up (_the proxy returns an authentication error message_). However I can make such a request successfully with Postman. Could this be RestSharp-related or a .NET Core (v3.1) issue? 🤔
