### ISSUE TITLE
Does Not work with Windows 10 Version 10.0.17763.1 

### ISSUE THREAD

**Issue by czupet** [restsharp/RestSharp#1182]
## Actual Behavior
Error: 
Operation is not supported on this platform.
in response variable.

## Steps to Reproduce the Problem

  1.
 var request = new RestRequest("getserver/data1")
                {
                    OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; }
                };

                IRestResponse<string> response = await _client.ExecuteGetTaskAsync<string>(request, _cancellationTokenSource.Token);
  2.
  3.

## Specifications

  - Version:
106.4.2
  - Platform:
Windows 10 Version 10.0.17763.1 
UWP Program.
  - Subsystem:
64bit

## StackTrace
{System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.ConfigureAsyncWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternalAsync(String method, Action`1 callback)}

<details>

V106.4.2 for UWP Does not work with previous version of Windows 10 either, 
RestSharp V106.3.1 does work with previous version of Windows 10, but does not work with Version 10.0.17763.1 

</details>

**Comment by Enngage** [comment]
I'm getting the same exception :(

**Comment by czupet** [comment]
And of course compiled application will not work also.  So if you had an application that was working and updated Windows 10 to V 10.0.17763.1, your application will not connect to WebAPI.

**Comment by Psypher9** [comment]
Possibly a duplicate of #1179?

**Comment by czupet** [comment]
It's possible, but this is an UWP application.

**Comment by alexeyzimarev** [comment]
If you all cooperate, maybe you can fix this? I have no Windows.

**Comment by czupet** [comment]
Unfortunately like most of the people here I have not time to spare, I have a project going into production this coming Monday, and I am just hopping nobody has installed the new version of Windows.
I know this sounds really bad, because I am expecting someone else to fix this for me, but this might take me a lot of hours just to figure out how RestSharp works and no guarantees I will be able to fix the problem.  The guy with the loudest mouth (me) will be contributing nothing, sorry about that.  I am trying to add HttpClient (RestSharp replacement) to my project so I have some kind of backup for this coming Monday.  At best I can offer it to test a fix if someone has one.

**Comment by alexeyzimarev** [comment]
Ok, thanks to @Psypher9 it should now be working in 106.5. I am not sure if the default proxy would be discovered on unsupported platforms though. Feel free to leave more feedback.

**Comment by czupet** [comment]
I am getting the same error with 106.5 as before, it was not fixed, it does not work with UWP apps and any version of Windows 10

**Comment by Psypher9** [comment]
@czupet, I'll take a look at UWP and see why you would still be getting that exception, because I was trying to catch that specific exception and handle it.

Just to clarify, is your stack trace the very same?

**Comment by czupet** [comment]
Looks the same

StackTrace = "   at System.Net.SystemWebProxy.GetProxy(Uri destination)\r\n   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)\r\n   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)\r\n   at System....

   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.ConfigureAsyncWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternalAsync(String method, Action`1 callback)

**Comment by Psypher9** [comment]
Since the exception is being thrown at the `HttpWebRequest.GetSystemWebProxy()` of

```csharp 
 http.Proxy = Proxy ?? (WebRequest.DefaultWebProxy ?? HttpWebRequest.GetSystemWebProxy());
```

Could we make a compiler directive wrap around that line if the platform running RestSharp is `WINDOWS_APP`, `NETCOREAPP2_0`, or `NETCOREAPP2_1` and if so just set the `http.Proxy` to `null`? I'm thinking that might help. I'd need to test it on a few test apps though.

**Comment by alexeyzimarev** [comment]
It was like this before, for `NETSTANDARD`. But then it started to work on some platform. This is just a big mess from .NET Core.

**Comment by alexeyzimarev** [comment]
`WINDOWS_APP` won't work since these are compiler directive, not run-time directives. However, we could put a condition on the call itself for Windows.

**Comment by alexeyzimarev** [comment]
Try this one https://www.nuget.org/packages/RestSharp/106.5.1

**Comment by czupet** [comment]
Operation is not supported on this platform.

   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.ConfigureAsyncWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternalAsync(String method, Action`1 callback)

**Comment by alexeyzimarev** [comment]
So it is not Windows then
```csharp
            if (http.Proxy == null && !RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                http.Proxy = WebRequest.GetSystemWebProxy();
```

**Comment by alexeyzimarev** [comment]
Won't it be great if you @czupet just download the source code and do a reference to the dll, then play around with those compiler directives? I am sitting here with fever and headache and keep getting exceptions, that's not very helpful. I cannot test it, I have no Windows or UWP application. I will do one more version and then give up. I'd really love if people that experience issues spend a little more time to help, like @Psypher9 did.

**Comment by alexeyzimarev** [comment]
https://www.nuget.org/packages/RestSharp/106.5.2 is my last attempt for today.

**Comment by czupet** [comment]
Same error as before.
Unfortunately I have no time until later this week to do any kind of troubleshooting.  I have never looked at the source code for the RestSharp so I don't even know how long it would take me to even figure out what's what.  And Microsoft will be pushing out new version of Windows 10 tomorrow.

**Comment by Psypher9** [comment]
@czupet the lines you will want to focus on are [Lines 577- 586 of RestClient.cs](https://github.com/restsharp/RestSharp/blob/1e2b9b95ff0221c2efe296464748e5889c2f1366/RestSharp/RestClient.cs#L577-L586). This is the only reference to `WebRequest.GetSystemWebProxy()` which is where the exception in `System.Net.SystemWebProxy.GetProxy(Uri)` is originating.

**Comment by alexeyzimarev** [comment]
That’s correct. There is only one call for that method and it has been taken out from the .NET Standard library in 106.5.2. I have no idea what the issue is.

**Comment by alexeyzimarev** [comment]
The time spent to discuss this issue and to try downloading new versions and post the exception exceeds the required debug time for the order of magnitude. @czupet you'd need 20-30 minutes max to find out what is wrong there. I have a full-time job, I am writing a book, I will speak at a conference next month and I am sick. Definitely, I've spent more time than I possibly could on this particular issue.

**Comment by czupet** [comment]
After doing some more debugging I found this, but still do not know how to fix this.

The error occurs in Http.Sync.cs at line 162.
with the following exception:

An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established

InnerException = {System.Exception: The text associated with this error code could not be found.

A connection with the server could not be established

Stack trace
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)

**Comment by alexeyzimarev** [comment]
You previously said that it was failing with Platform not supported exception and that was what we’ve been fixing?

**Comment by czupet** [comment]
That's the error I get when I add the RestSharp as a NuGet package, but when I add the RestSharp as a library I get the "A connection with the server could not be established" error.

**Comment by czupet** [comment]
If I run the UWP app on Windows 10 Version 10.0.17134.345 the NuGet package anything over 106.3.1 fails with Platform not supported error.  But if I load the RestSharp as a library all of the versions work. But nothing works on Windows 10 Version 10.0.17763.55, the NuGet package fails with Platform not supported and the library fails with Connection error.

**Comment by alexeyzimarev** [comment]
So, this issue is not about .NET Core or .NET Standard. Visual Studio prefers adding a reference to the .NET Framework 4.5.2 version but the UWP interop or whatever that is doesn't have the proxy detection method. That is clearly a Microsoft issue for me. I don't know how it can be solved, to be honest.

**Comment by alexeyzimarev** [comment]
Fixed in 106.5.3

**Comment by czupet** [comment]
It works on Windows 10 Version 10.0.17134.345 UWP application, but it still does not work on Windows 10 Version 10.0.17763.55

Getting the following error message.

An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established

**Comment by alexeyzimarev** [comment]
I tested it on the latest Windows version and UWP app and it works.

**Comment by jnyrup** [comment]
@alexeyzimarev Which version of Windows 10 do you regard as the latest?
10.0.17763.55 is the October 2018 version of Windows 10, but it's not rolled out to everyone yet (I'm on 10.0.17134.345 April 2018 update).

**Comment by alexeyzimarev** [comment]
![screenshot 2018-10-15 at 08 52 15](https://user-images.githubusercontent.com/2821205/46934338-a7c15e80-d057-11e8-9446-256e00d019ea.png)

**Comment by alexeyzimarev** [comment]
The latest that is publicly available at the moment for the majority of users.

I tested without proxy and with a proxy. I have no issues getting to a service that is hosted publicly on the Internet.

**Comment by alexeyzimarev** [comment]
This is my code https://github.com/alexeyzimarev/RestSharp.UWP

**Comment by czupet** [comment]
The latest that is publicly available since October 9th (that's when Microsoft started pushing out the update) for all users is Version 10.0.17763.55 - it's an official production release.  And that's the version RestSharp does not work with in UWP applications.

**Comment by czupet** [comment]
The error on Windows 10 Version 10.0.17763.55 occurs only when I am on VPN, when I went into the office the error went away.  I've tried the Microsoft VPN and the Cisco VPN and the results were the same.
So I don't know if it's the VPN problem, Windows 10 problem or RestSharp problem.  But I can't use RestSharp until this gets resolved.  I have not tried the HttpClient() yet to see if I get the same results.

**Comment by czupet** [comment]
Same error with HttpClient on VPN and Windows 10 Version 10.0.17763.55, works fine on none VPN web service.

 HttpClient client = new HttpClient();
            string path = "<Any REST Web Service Address on your VPN network>";
            HttpResponseMessage response = await client.GetAsync(path);
            if (response.IsSuccessStatusCode)
            {
                var res = await response.Content.ReadAsStringAsync();
            }

**Comment by Psypher9** [comment]
Yeah in that case, this is definitely not a RestSharp issue.

**Comment by mlockett42** [comment]
I have been suffering from this issue (connecting to a server on a VPN with RestSharp in a UWP appp)

I needed to add privateNetworkClientServer (aka Private Networks Client & Server) to the capabilities

I also updated RestSharp from version 106.6.10 to 106.11.4
