### ISSUE TITLE
RestRequest.JsonSerializer = new JsonCustomSerializer<T>() not working

### ISSUE THREAD

**Issue by andrewkip** [restsharp/RestSharp#1251]
Hello!

It seems that in new version RestSharp 106.6.3.0 ovveriding JSon Serializer in RestRequest.JsonSerializer not working
for example:
var request = new RestRequest
            {
                Method = Method.POST,
                RequestFormat = DataFormat.Json,
                JsonSerializer = new JsonCustomSerializer<T>()
        };

request.AddJsonBody(obj);

but JsonCustomSerializer.Serialize not calling...
and  ContentType of Body not equal to JsonCustomSerializer.ContentType

have to do dirty Hack: 
request.AddJsonBody( request.JsonSerializer.Serialize(obj));

**Comment by alexeyzimarev** [comment]
The Serialize method is not called when you use `AddJsonBody` but when you execute the request. Are you sure that your serializer is _never_ called?

**Comment by andrewkip** [comment]
I've checked again Serialize method is not calling when I execute request too.

By the way. If you say that Serialize is called when request executes How can accompliesh following scenario: 

I've serialized by DataContractJsonSerializer (System.Runtime.Serialization.Json;) class Class1  with property Prop1 with alternative name for serialization prop_1 (see below]). 
How to put this properly named (with prop_1) serialized object into the body? If I addJsonBody it serialized as object with Prop1?

[DataContract]
    public class Class1
    {
        [DataMember(Name = "prop_1")]
        public string Prop1 { get; set; }
    }

**Comment by alexeyzimarev** [comment]
I am not sure what you mean. How the moment when your body object is serialized affect the serialization outcome?

**Comment by alexeyzimarev** [comment]
Fixed in 106.6.4

**Comment by andrewkip** [comment]
Still not working. 
I need Class1 serialized into the request body (as I can see in AddJsonBiody method) in proper way, so I create custom serializer and adjust custom serializer to RestRequest JsonSerializer, but when I call AddJsonBody(obj) then Serialize mthod of custom serializer is not called.  
How ever the summary from RestRequest.cs concerning  RestRequest.JsonSrializer sounds like this method must be called - correct me if I wrong.

Here is the summary:
/// <summary>
        ///     Serializer to use when writing JSON request bodies. Used if RequestFormat is Json.
        ///     By default the included JsonSerializer is used (currently using JSON.NET default serialization).
        /// </summary>
        public ISerializer JsonSerializer { get; set; }

**Comment by andrewkip** [comment]
I've found the problem:

I've defined ContentType in my Custom serializer as application/json but

in RestSharp\RestRequestExtensions.cs
in internal static class RestRequestExtensions
at line 22

var requestSerializer = serializers.FirstOrDefault(x => x != null && x.ContentType == body.ContentType);

body.ContentType is null but x.ContentType is application/json

so if I define ContentType as null in my serializer evrething works fine.

Where do I have to define body ContentType?
Or should I define in custom serializer ContentType as null?

**Comment by alexeyzimarev** [comment]
Cool, thank you for helping me finding the issue. I need to take into account the request content type. Maybe to set the parameter content type to the request content type if it is set.

**Comment by alexeyzimarev** [comment]
Let me add some tests for it. The client serializer in your case works as expected, but the request-level serializer should supersede it.

**Comment by e-tobi** [comment]
Just stumbled upon the same issue. My workaround was to use restClient.UseSerializer() with a custom implementation of IRestSerializer for Newtonsoft.Json:

    public class NewtonsoftJsonRestSerializer : IRestSerializer
    {
        private readonly JsonSerializer _serializer;

        public NewtonsoftJsonRestSerializer()
        {
            _serializer = new JsonSerializer
            {
                MissingMemberHandling = MissingMemberHandling.Ignore,
                NullValueHandling = NullValueHandling.Include,
                DefaultValueHandling = DefaultValueHandling.Include
            };
        }

        public string Serialize(object obj)
        {
            using (var stringWriter = new StringWriter())
            {
                using (var jsonTextWriter = new JsonTextWriter(stringWriter))
                {
                    _serializer.Serialize(jsonTextWriter, obj);

                    return stringWriter.ToString();
                }
            }
        }

        public string ContentType { get; set; } = "application/json";

        public T Deserialize<T>(IRestResponse response)
        {
            var content = response.Content;

            using (var stringReader = new StringReader(content))
            {
                using (var jsonTextReader = new JsonTextReader(stringReader))
                {
                    return _serializer.Deserialize<T>(jsonTextReader);
                }
            }
        }

        public string Serialize(Parameter parameter) => Serialize(parameter.Value);

        public string[] SupportedContentTypes { get; } =
        {
            "application/json", "text/json", "text/x-json", "text/javascript", "*+json"
        };

        public DataFormat DataFormat { get; } = DataFormat.Json;
    }

**Comment by tomgallard** [comment]
We are having this issue too. Please reopen this issue, as it has caused breaking changes to existing implementations, and is not fixed as of 106.6.5

**Comment by andrewkip** [comment]
> Let me add some tests for it. The client serializer in your case works as expected, but the request-level serializer should supersede it.

As I can see - yes.

**Comment by vmalinovskiy** [comment]
The same for me. Do you plan to fix this?

**Comment by joshuaRMS** [comment]
@e-tobi thanks a lot for this work around. This works great for me!

**Comment by shearer3000** [comment]
hi - was this ever fixed?

**Comment by OlegTontici** [comment]
This is what solved it for me:
1) Create your own serializer implementation by inheriting from  ISerializer
2) In your RestRequest : 
RequestFormat = DataFormat.Json,
JsonSerializer = new InstanceOfYourSerializer()
3) In "InstanceOfYourSerializer" - set value of the "ContentType" to "application/json"

Why? Because it has to know for which content type this serializer is intended for

**Comment by alexeyzimarev** [comment]
@tomgallard @vmalinovskiy it is the only way to implement the client level serializer, which was a highly requested feature.

The serializer is and will always be called when the request is performed and _not_ when you call `AddJsonBody`. I explained already why is that. When you form a request, it has no access to the RestClient instance and doesn't know if the client has any custom serializer configured.

New serialization libraries for NewtonsoftJson, System.Text.Json and UtfJson have hundreds of thousands of downloads and if we "fix" it, all those developers will be affected.

I still struggle to understand what exactly is the issue. You can still use the request-level serializer and we have tests for this case and they are all green. If you see a particular issue - please try to troubleshoot it and propose a fix.

**Comment by SmartifyAI** [comment]
Does below instruction from documentation work at all? I keep getting a null body in the Request. However a JObject sometimes works and fails frequently

```
Do not set content type headers or send JSON string or some sort of JObject instance to AddJsonBody, it won't work!

Here is the example:

```
var param = new MyClass { IntData = 1, StringData = "test123" };
request.AddJsonBody(param);
```
```

**Comment by OlehUdovytskyi** [comment]
The only thing that works with 106.11.4 is **_AddJsonBody(JsonConvert.SerializeObject(obj, SerializerSettings))_**. In all other cases my requests are not deserialized correctly.
