### ISSUE TITLE
OAuth 1.0a callback parameter is not encoded properly

### ISSUE THREAD

**Issue by egorpavlikhin** [restsharp/RestSharp#1437]
## Expected Behavior
106.9.0
`Authorization Header is present: OAuth oauth_callback="http%3A%2F%2Flocalhost%3A3003%2Ftwitter%2Fcallback",oauth_consumer_key="",oauth_nonce="2g8x58qm0fjvclfr",oauth_signature="NHwy1rvbOC77Pp%2BYGtVVBipRWIc%3D",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1583741026",oauth_version="1.0"`

## Actual Behavior
106.10.1
`Authorization Header is present: OAuth oauth_callback="http://localhost:3003/twitter/callback",oauth_consumer_key="",oauth_nonce="mg6z7nerh1uii8vm",oauth_signature="IXCbkpr4k%2BChQaAGfhJRdRWbBCU%3D",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1583738501",oauth_version="1.0"`

## Steps to Reproduce the Problem
Use this code
https://github.com/restsharp/RestSharp/blob/9c4a0c2e3a044acc381eb44ca6fce30b07b76fd6/test/RestSharp.IntegrationTests/AuthenticationTests.cs#L28
But change
`Authenticator = OAuth1Authenticator.ForRequestToken("CONSUMER_KEY", "CONSUMER_SECRET")`
to 
`Authenticator = OAuth1Authenticator.ForRequestToken("CONSUMER_KEY", "CONSUMER_SECRET", "http://localhost:3003/twitter/callback")`

and 
`var response = client.Execute(request);`
to
`var response = await client.ExecuteAsync(request);`

## Specifications

  - Version: 106.10.1
  - Platform: Windows
  - Subsystem: .Net Core

**Comment by alexeyzimarev** [comment]
I believe it was already fixed. Can you check with the latest preview package?

**Comment by richardversluis** [comment]
I also encountered this issue. I tried the latest preview package (`Version 106.11.5-alpha.0.2`) and the problem still persists.

**Comment by speedy78** [comment]
I also encountered this issue, but using the version 106.8.0 it works fine

**Comment by alexeyzimarev** [comment]
@speedy78 RestSharp is an open-source library and questions like yours are considered offensive.

**Comment by alexeyzimarev** [comment]
@egorpavlikhin can you try 106.11.5-alpha.0.17? The Twitter test worked for me.

**Comment by speedy78** [comment]
Yes with 106.11.5-alpha.0.17 it works fine.

**Comment by alexeyzimarev** [comment]
Awesome. I will prepare a stable version.
