### ISSUE TITLE
Using RestSharp with streaming endpoint

### ISSUE THREAD

**Issue by JanOonk** [restsharp/RestSharp#1672]
Does RestSharp v106.15.0 work with a streaming endpoint? For example Twitter has an https://api.twitter.com/2/tweets/search/stream endpoint which streams tweet(s) matching certain rule(s) created with another endpoint.
Using `curl https://api.twitter.com/2/tweets/search/stream -H "Authorization: Bearer ...."` this works.
I also got it to work when using `WebClient` in C#:
```csharp
webClient = new WebClient();
webClient.Headers[HttpRequestHeader.Authorization] = $"Bearer {settings.Twitter.BearerToken}";
webClient.OpenReadCompleted += (sender, openReadCompletedEventArgs) =>
{
    Stream stream = openReadCompletedEventArgs.Result;
    using (var reader = new StreamReader(stream))
    {
        while (!reader.EndOfStream)
        {
            string json = reader.ReadLine();
            Console.WriteLine(json);
        }
    }
};
webClient.OpenReadAsync(new Uri(settings.Twitter.FilteredStreamUrl.AbsoluteUri));
```

But I can't get it working using RestSharp:
```csharp
var client = new RestClient($"{settings.Twitter.FilteredStreamUrl}");
var request = new RestRequest(RestSharp.Method.GET);
request.RequestFormat = DataFormat.Json;
request.AddHeader("Content-Type", "application/json");
request.AddHeader("Authorization", "Bearer " + settings.Twitter.BearerToken);
//request.AdvancedResponseWriter = (stream, statuscode) =>
request.ResponseWriter = (stream) =>
{
    using (var reader = new StreamReader(stream))
    {
        while (!reader.EndOfStream)
        {
            //Console.WriteLine(statuscode);
            string json = reader.ReadLine();
            Console.WriteLine(json);
        }
    }
};
client.Execute(request);
```

 Does RestSharp support streaming endpoints? Or am I doing something wrong in my code?

**Comment by alexeyzimarev** [comment]
What do you mean by "can't get it working"?

**Comment by JanOonk** [comment]
The code compiles, can make a connection but I dont receive data.

**Comment by alexeyzimarev** [comment]
I'd suggest trying v107 preview. The version you use relies on heavy legacy stuff. There's an async stream reader there, you don't need to use the response writer, but call `client.DownloadStreamAsync()`

**Comment by JanOonk** [comment]
Ah ok thanks. What's the easiest way? Or only by checking out the branch v107-preview ?

**Comment by alexeyzimarev** [comment]
What do you mean? All the preview packages are on NuGet.

**Comment by JanOonk** [comment]
Ah thanks I missed the checkbox include prerelease. Meanwhile I already managed to compile the source and install the dll :)
For reference for other readers:
![image](https://user-images.githubusercontent.com/13236774/146975486-7fac15b0-5809-45cf-acbb-eec0cd2cc80e.png)

**Comment by JanOonk** [comment]
Noticed your #1674... cool. Does that mean its impossible currently? Because I am still struggling.

This is what I tried:
```csharp
            var client = new RestClient("https://api.twitter.com/2/tweets/search/stream");
            var request = new RestRequest(Method.Get)
            {
                ResponseWriter = stream =>
                {
                    using (var reader = new StreamReader(stream))
                    {
                        while (!reader.EndOfStream)
                        {
                            //Console.WriteLine(statuscode);
                            string json = reader.ReadLine();
                            Console.WriteLine(json);
                        }
                    }
                    return stream;
                }
            };

            request.RequestFormat = DataFormat.Json;
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", "Bearer " + "...");

            await client.DownloadStreamAsync(request);

```

Whatever client method I call (DownloadDataAsync, DownloadStreamAsync, ExecuteAsync) I always get this error:
![image](https://user-images.githubusercontent.com/13236774/147055014-5cc527c7-20b2-4bb2-a943-1526a4e1a891.png)

**Comment by alexeyzimarev** [comment]
It should be possible with `DownloadStreamAsync`. Which package version do you use? This issue (https://github.com/restsharp/RestSharp/issues/1664) was fixed a few days ago.

The reason for this exception is that you set the `Content-Type` header for a request without content. Why are you doing that?

Also, normally you would use the `JwtAuthenticator` instead of adding the `Authorization` header.

With RestSharp, in 90% of cases you _do not need_ to set any request headers.

Next, you need to remove the response writer. `DownloadStreamAsync` returns a stream. You should do what you do in the response writer loop, but use the stream returned by `DownloadStreamAsync` instead.

**Comment by JanOonk** [comment]
Thanks for the tips. I am now using `107.0.0-preview.13` and I dont get the error but still doesn't work though.
It never makes it passed the `DownloadStreamAsync` call.

```csharp
var client = new RestClient("https://api.twitter.com");
var request = new RestRequest("/2/tweets/search/stream", Method.Get);

JwtAuthenticator authentication = new JwtAuthenticator("...");
client.Authenticator = authentication;

Stream stream = client.DownloadStreamAsync(request).Result;

using (var reader = new StreamReader(stream))
{
    while (!reader.EndOfStream)
    {
        string json = reader.ReadLine();
        Console.WriteLine(json);
    }
}
```

**Comment by alexeyzimarev** [comment]
Honestly, I never tried using neither `RestClient` nor `HttpClient` for streaming endpoints. I will try this Twitter API endpoint during the week.

**Comment by JanOonk** [comment]
No rush since I have a workaround using `WebClient` (see my very first code snippet in my first post). But I like RestSharp and use it in my whole project so I want to remove WebClient for consistency and because of the extra dependency.
Would be cool if RestSharp would support these kind of endpoints.
thanks for your time

**Comment by alexeyzimarev** [comment]
Basically, this code works without any changes in the current version:

```csharp
    public async Task SearchStream() {
        var request = new RestRequest("tweets/search/stream") { CompletionOption = HttpCompletionOption.ResponseHeadersRead };
        var stream  = await _client.DownloadStreamAsync(request);

        var reader = new StreamReader(stream!);
        while (!reader.EndOfStream) {
            var x = await reader.ReadLineAsync();
            Console.WriteLine(x);
        }
    }
```

**Comment by alexeyzimarev** [comment]
From 107.2 you can use `StreamJsonAsync<T>`. There's an example here:
https://github.com/restsharp/RestSharp/blob/cd4c434927fac44ffe18f01642a618f06b07418e/test/RestSharp.InteractiveTests/TwitterClient.cs#L58-L64
